language: node_js
node_js:
  - "10"
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
services:
  - docker
before_install:
  - ./install_compose.sh
script:
  - export REACT_APP_DOMAIN=backend-demo-app
  - docker-compose up -d
  - sleep 20
  - docker ps
  - docker-compose exec frontend sh -c "npm test"
